# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hgiesel/Developer/repos/anki_asset_manager/designer/config.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Config(object):
    def setupUi(self, Config):
        Config.setObjectName("Config")
        Config.resize(826, 489)
        self.gridLayout = QtWidgets.QGridLayout(Config)
        self.gridLayout.setObjectName("gridLayout")
        self.cancelButton = QtWidgets.QPushButton(Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancelButton.sizePolicy().hasHeightForWidth())
        self.cancelButton.setSizePolicy(sizePolicy)
        self.cancelButton.setAutoDefault(False)
        self.cancelButton.setObjectName("cancelButton")
        self.gridLayout.addWidget(self.cancelButton, 2, 5, 1, 1)
        self.saveButton = QtWidgets.QPushButton(Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveButton.sizePolicy().hasHeightForWidth())
        self.saveButton.setSizePolicy(sizePolicy)
        self.saveButton.setAutoDefault(False)
        self.saveButton.setObjectName("saveButton")
        self.gridLayout.addWidget(self.saveButton, 2, 4, 1, 1)
        self.wbButton = QtWidgets.QPushButton(Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wbButton.sizePolicy().hasHeightForWidth())
        self.wbButton.setSizePolicy(sizePolicy)
        self.wbButton.setDefault(True)
        self.wbButton.setObjectName("wbButton")
        self.gridLayout.addWidget(self.wbButton, 2, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 2, 1, 1, 2)
        self.tabWidget = QtWidgets.QTabWidget(Config)
        self.tabWidget.setObjectName("tabWidget")
        self.html = QtWidgets.QWidget()
        self.html.setObjectName("html")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.html)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.configWidgetHtml = HTMLTab(self.html)
        self.configWidgetHtml.setObjectName("configWidgetHtml")
        self.verticalLayout_2.addWidget(self.configWidgetHtml)
        self.tabWidget.addTab(self.html, "")
        self.javascript = QtWidgets.QWidget()
        self.javascript.setObjectName("javascript")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.javascript)
        self.verticalLayout.setObjectName("verticalLayout")
        self.configWidget = ScriptTab(self.javascript)
        self.configWidget.setObjectName("configWidget")
        self.verticalLayout.addWidget(self.configWidget)
        self.tabWidget.addTab(self.javascript, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 6)
        self.helpButton = QtWidgets.QPushButton(Config)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.helpButton.sizePolicy().hasHeightForWidth())
        self.helpButton.setSizePolicy(sizePolicy)
        self.helpButton.setAutoDefault(False)
        self.helpButton.setObjectName("helpButton")
        self.gridLayout.addWidget(self.helpButton, 2, 0, 1, 1)

        self.retranslateUi(Config)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Config)

    def retranslateUi(self, Config):
        _translate = QtCore.QCoreApplication.translate
        Config.setWindowTitle(_translate("Config", "Script Manager Settings"))
        self.cancelButton.setText(_translate("Config", "Cancel"))
        self.saveButton.setText(_translate("Config", "Save"))
        self.wbButton.setText(_translate("Config", "Write To Templates"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.html), _translate("Config", "HTML Template"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.javascript), _translate("Config", "JavaScript"))
        self.helpButton.setText(_translate("Config", "Help"))
from ..html_tab import HTMLTab
from ..script_tab import ScriptTab
