# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/hgiesel/Developer/repos/anki_asset_manager/designer/settings.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName("Settings")
        Settings.setWindowModality(QtCore.Qt.WindowModal)
        Settings.resize(290, 111)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        Settings.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(Settings)
        self.gridLayout.setObjectName("gridLayout")
        self.buttonBox = QtWidgets.QDialogButtonBox(Settings)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 4, 1, 1, 1)
        self.version_info = QtWidgets.QLabel(Settings)
        self.version_info.setObjectName("version_info")
        self.gridLayout.addWidget(self.version_info, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(Settings)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 2, 0, 1, 2)
        self.remove_cards = QtWidgets.QCheckBox(Settings)
        self.remove_cards.setObjectName("remove_cards")
        self.gridLayout.addWidget(self.remove_cards, 1, 0, 1, 2)
        self.add_assets = QtWidgets.QCheckBox(Settings)
        self.add_assets.setObjectName("add_assets")
        self.gridLayout.addWidget(self.add_assets, 0, 0, 1, 2)

        self.retranslateUi(Settings)
        self.buttonBox.accepted.connect(Settings.accept)
        self.buttonBox.rejected.connect(Settings.reject)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        _translate = QtCore.QCoreApplication.translate
        Settings.setWindowTitle(_translate("Settings", "Asset Manager Settings"))
        self.version_info.setText(_translate("Settings", "VERSION_INFO"))
        self.remove_cards.setText(_translate("Settings", "Remove \"Cards...\" button from Editor"))
        self.add_assets.setText(_translate("Settings", "Add \"Assets...\" button to Editor"))
